// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package database

import ()

type Account struct {
	PersonID   string
	FirstName  string
	LastName   string
	WebAddress string
	DateBirth  string
}
