// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package database

import (
	"database/sql"
)

type Account struct {
	ID         int64
	PersonID   string
	FirstName  string
	LastName   string
	WebAddress sql.NullString
	DateBirth  sql.NullTime
}
