apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lab-app
  name: challengeapp
  labels:
    app: challengeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challengeapp
  template:
    metadata:
      labels:
        app: challengeapp
    spec:
      containers:
        - name: challengeapp
          image: '${docker_image}'
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              memory: 1Gi
              cpu: 500m
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: postgres-db-config