apiVersion: v1
kind: Service
metadata:
  namespace: lab-app
  name: webproxy-ingress-challengeapp
  labels:
    app: challengeapp
spec:
  type: ClusterIP
  selector:
    app: challengeapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080