apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: lab-app
  name: postgresql-volume-claim
  labels:
    app: postgresql
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi