apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: lab-app
  name: postgresql-volume-claim
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgresql"