name: Deploy to heroku app

on:
  push:
    branches:
      - main

jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Config file access
        run: |
          echo -e '{
              "database": {
                  "url": "://HEROKU_DB_USER:HEROKU_DB_PASS@HEROKU_DB_HOST:HEROKU_DB_PORT/HEROKU_DB_NAME"
              },
              "server": {
                  "port": "8080"
              }
          }' > config.json
          sed -i -e 's/HEROKU_DB_USER/'${{ secrets.HEROKU_DB_USER }}'/g' \
                 -e 's/HEROKU_DB_PASS/'${{ secrets.HEROKU_DB_PASS }}'/g' \
                 -e 's/HEROKU_DB_HOST/'${{ secrets.HEROKU_DB_HOST }}'/g' \
                 -e 's/HEROKU_DB_PORT/'${{ secrets.HEROKU_DB_PORT }}'/g' \
                 -e 's/HEROKU_DB_NAME/'${{ secrets.HEROKU_DB_NAME }}'/g' config.json
          cat config.json
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_MAIL_USER }}