on: [push, pull_request]
name: Run test suite
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download swaggo
      run: go install github.com/swaggo/swag/cmd/swag@v1.8.4
    - name: Install swaggo
      run: swag init -g cmd/app/main.go -o docs
    - name: Load secret
      run: export APP_POSTGRES_PASSWORD=${{ secrets.APP_POSTGRES_PASSWORD }}
    - name: Test
      run: go mod tidy && cd api/accounts && go test -v -coverprofile=coverage.txt -covermode=atomic
    - name: Upload coverage report
      uses: codecov/codecov-action@v1.0.2
      with:
        token: 7e788ea1-d20b-4832-94b6-5b716930ef0a
        file: ./coverage.txt
        flags: unittests
        name: codecov-umbrella