on: [push, pull_request]
name: Run test suite
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run db background
      run: docker ps && docker-compose -f stack.yaml -f stack.dev.yaml up -d
    - name: Check db
      run: docker exec db psql -U postgres -c "\dt+"
    - name: Exec tests
      run: |
            export APP_POSTGRES_PASSWORD=${{ secrets.APP_POSTGRES_PASSWORD }} \
            && cd api/accounts && go test -v -coverprofile=coverage.txt -covermode=atomic
    - name: Upload coverage report
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{ secrets.CODECOV_API_KEY }}
        file: ./coverage.txt
        flags: unittests
        name: codecov-umbrella